name: Trigger auto deployment for container-app-yoevt5fx7tr5u

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-yoevt5fx7tr5u-AutoDeployTrigger-5c1ce9fa-1c09-4bf1-874d-4f5ac0f56385.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPYOEVT5FX7TR5U_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPYOEVT5FX7TR5U_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPYOEVT5FX7TR5U_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPYOEVT5FX7TR5U_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPYOEVT5FX7TR5U_REGISTRY_PASSWORD }}
          containerAppName: container-app-yoevt5fx7tr5u
          resourceGroup: todonodejspgsqlgoogleauth88bc84fc
          imageToBuild: default/container-app-yoevt5fx7tr5u:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


